name: Build libfuzzer-dotnet

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["master"]

env:
  dotnet-version: 9.0

jobs:
  build-windows:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: clang -Werror -O2 -fsanitize=fuzzer libfuzzer-dotnet-windows.cc -o libfuzzer-dotnet-windows.exe
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Run libFuzzer tests
        run: cp libfuzzer-dotnet-windows.exe libfuzzer-dotnet.exe && .\test.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: libfuzzer-dotnet-windows
          path: libfuzzer-dotnet-windows.exe

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Download LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
      - name: Build
        run: clang-20 -Werror -O2 -fsanitize=fuzzer libfuzzer-dotnet.cc -o libfuzzer-dotnet-ubuntu
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Run libFuzzer tests
        shell: pwsh
        run: cp libfuzzer-dotnet-ubuntu libfuzzer-dotnet && .\test.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: libfuzzer-dotnet-ubuntu
          path: libfuzzer-dotnet-ubuntu

  build-debian:
    runs-on: ubuntu-latest
    container: debian:bookworm

    steps:
      - uses: actions/checkout@v4
      - name: Download LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
      - name: Build
        run: clang-20 -Werror -O2 -fsanitize=fuzzer libfuzzer-dotnet.cc -o libfuzzer-dotnet-debian
      - uses: actions/upload-artifact@v4
        with:
          name: libfuzzer-dotnet-debian
          path: libfuzzer-dotnet-debian
